export type ProductType = 'consoles' | 'games' | 'gear' | 'top-ups';

export type Product = {
  id: string;
  name: string;
  type: ProductType;
  label: string;
  price: number;
  originalPrice?: number;
  glyph: string;
  wash: string;
  badge?: string;
  spec?: string;
  rating: number;
  reviewsCount: number;
  inStock: boolean;
  shortDesc: string;
  fullDesc: string;
  features: string[];
  specs: { label: string; value: string }[];
  category: 'accessories' | 'games' | 'consoles' | 'top-ups';
  subCategory: string;
  coverImage?: string;
  platform?: 'pc' | 'playstation' | 'xbox' | 'nintendo';
  discountBadge?: string;
  // Specific for accessories
  colors?: { name: string; hex: string; available?: boolean }[];
  // Specific for games
  genre?: string[];
  editions?: { id: string; name: string; price: number; perks: string[] }[];
  metacritic?: number;
  esrb?: string;
  releaseDate?: string;
  publisher?: string;
  developer?: string;
  enhancements?: string[];
  backdropWash?: string;
};

export const ACCESSORIES: Product[] = [
  {
    id: 'dualsense-edge',
    name: 'DualSense Edge™ Wireless Controller',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Pro Controller',
    price: 199.99,
    originalPrice: 219.99,
    glyph: 'EDGE',
    wash: 'hsl(285 85% 72% / .32)',
    badge: 'PRO HARDWARE',
    spec: 'Replaceable Stick Modules · Remappable Back Buttons',
    rating: 4.95,
    reviewsCount: 2450,
    inStock: true,
    shortDesc: 'Ultra-customizable pro controller built for high-performance esports with remappable back buttons and swappable modules.',
    fullDesc: 'Gain an edge in gameplay by crafting your own custom controls to fit your playstyle. Built with high performance and personalization in mind, the DualSense Edge wireless controller invites you to craft your own unique gaming experience so you can play your way. Includes customizable controls, swappable stick caps, remappable back buttons, and tuned trigger travel distances.',
    features: [
      'Ultra-customizable controls with dedicated Fn buttons to quickly swap profiles',
      'Changeable stick caps and replaceable stick modules for longevity',
      'Configurable back buttons (half-dome and lever options included)',
      'Adjustable trigger stops and deadzone tuning via PS5 system menu',
      'DualSense core features: Haptic feedback, adaptive triggers, and motion sensors',
      'Braided USB-C cable with lockable connector housing and premium carrying case',
    ],
    specs: [
      { label: 'Connectivity', value: 'Bluetooth 5.1 & Low-Latency USB-C' },
      { label: 'Battery Life', value: 'Up to 8-10 Hours Continuous Play' },
      { label: 'Weight', value: '325g (Optimized Counter-Weighted)' },
      { label: 'Haptics', value: 'Dual Voice-Coil Actuators' },
      { label: 'Triggers', value: 'Adaptive Hall-Effect with Mechanical Stops' },
      { label: 'Audio', value: '3.5mm Hi-Res Audio Jack & Built-in Mic Array' },
    ],
    colors: [
      { name: 'White & Obsidian', hex: '#f8fafc', available: true },
      { name: 'Midnight Void', hex: '#18181b', available: true },
      { name: 'Sterling Silver', hex: '#94a3b8', available: false },
    ],
  },
  {
    id: 'pulse-elite',
    name: 'PULSE Elite™ Wireless Headset',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Headsets',
    label: 'Planar Magnetic Headset',
    price: 149.99,
    originalPrice: 169.99,
    glyph: 'ELITE',
    wash: 'hsl(272 90% 68% / .32)',
    badge: 'PLANAR MAGNETIC',
    spec: 'Custom Planar Drivers · Retractable Mic · 30H Battery',
    rating: 4.92,
    reviewsCount: 1280,
    inStock: true,
    shortDesc: 'Next-generation planar magnetic drivers deliver studio-grade acoustics and ultra-low latency PlayStation Link wireless audio.',
    fullDesc: 'Experience extraordinarily lifelike audio in your favorite games with planar magnetic drivers, and hear every sound with lightning-fast PlayStation Link lossless wireless connectivity. Enjoy up to 30 hours of battery life with quick charging, a fully retractable microphone with AI-enhanced noise rejection, and convenient charging hanger included.',
    features: [
      'Studio-inspired Planar Magnetic Drivers reproducing acoustic soundscapes with ultra-low distortion',
      'PlayStation Link™ technology for lightning-fast, lossless audio transmission',
      'AI-enhanced noise rejection powered by trained neural networks',
      'Multi-device connectivity: Listen to PS5 and Bluetooth phone audio concurrently',
      'Up to 30-hour battery life with 10-minute fast charging giving 2 hours play',
      'Includes charging hanger mount for sleek desk or wall storage',
    ],
    specs: [
      { label: 'Driver Type', value: 'Custom Planar Magnetic (Planar Ribbon)' },
      { label: 'Frequency Response', value: '10Hz – 40,000Hz Ultra-Wide' },
      { label: 'Wireless Protocol', value: 'PlayStation Link (Lossless 2.4GHz) & BT 5.3' },
      { label: 'Battery Capacity', value: '30 Hours (USB-C Fast Charging)' },
      { label: 'Microphone', value: 'Retractable Beamforming with AI Noise Suppression' },
      { label: 'Weight', value: '347g with Floating Comfort Suspension Strap' },
    ],
    colors: [
      { name: 'Void White', hex: '#f8fafc', available: true },
      { name: 'Cosmic Black', hex: '#0f172a', available: true },
    ],
  },
  {
    id: 'pulse-pro',
    name: 'Pulse 3D™ Wireless Headset',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Headsets',
    label: 'Setup Gear',
    price: 89.99,
    originalPrice: 99.99,
    glyph: 'PULSE',
    wash: 'hsl(245 75% 70% / .3)',
    badge: 'TEMPEST 3D',
    spec: 'Dual Noise-Cancelling Mics · 12H Battery',
    rating: 4.82,
    reviewsCount: 3120,
    inStock: true,
    shortDesc: 'Fine-tuned specifically for 3D Audio on PS5 consoles. Features refined design with dual noise-cancelling microphones.',
    fullDesc: 'Play in comfort with a wireless headset fine-tuned for 3D Audio on PS5 consoles. Featuring USB Type-C charging and dual noise-cancelling microphones, you can keep the party chat flowing with crystal-clear voice capture. Tailor the headset EQ settings directly from the PS5 control center.',
    features: [
      'Engineered for 3D Audio on PS5 with custom equalizer presets',
      'Dual hidden microphones positioned for optimal clear voice capture',
      'Easy-access audio controls: mic mute, master volume, and in-game chat balance',
      'Up to 12 hours of wireless play with the built-in rechargeable battery',
      'Connects easily to PS5 and PS4 consoles with the wireless USB adapter',
    ],
    specs: [
      { label: 'Drivers', value: '40mm Neodymium Acoustic Drivers' },
      { label: 'Compatibility', value: 'PS5, PS4, PC, Mac, PS VR2' },
      { label: 'Battery', value: '12 Hours Lithium-Ion USB-C' },
      { label: 'Headband', value: 'Comfort-Mesh Suspension Strap' },
    ],
    colors: [
      { name: 'Classic Two-Tone', hex: '#e2e8f0', available: true },
      { name: 'Midnight Black', hex: '#1e293b', available: true },
      { name: 'Gray Camo', hex: '#64748b', available: true },
    ],
  },
  {
    id: 'dual-sense',
    name: 'DualSense® Wireless Controller',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Controllers',
    price: 74.99,
    glyph: 'DS',
    wash: 'hsl(285 85% 72% / .3)',
    badge: 'HAPTIC CORE',
    spec: 'Dynamic Adaptive Triggers · Built-In Mic',
    rating: 4.88,
    reviewsCount: 4890,
    inStock: true,
    shortDesc: 'Discover a deeper gaming experience with the innovative PS5 controller, featuring haptic feedback and dynamic triggers.',
    fullDesc: 'The DualSense wireless controller for PS5 offers immersive haptic feedback, dynamic adaptive triggers, and a built-in microphone, all integrated into an iconic comfortable design. Feel physically responsive feedback to your in-game actions with dual actuators which replace traditional rumble motors.',
    features: [
      'Immersive Haptic Feedback replaces traditional rumble motors',
      'Dynamic Adaptive Triggers simulate tension and resistance of gear and weapons',
      'Integrated microphone array and 3.5mm headset jack',
      'Create button to capture and broadcast your most epic gaming moments',
      'Motion sensor built-in accelerometer and gyroscope for intuitive tilt control',
    ],
    specs: [
      { label: 'Feedback', value: 'Dual Voice Coil Haptic Actuators' },
      { label: 'Sensors', value: '6-Axis Gyroscope & Accelerometer' },
      { label: 'Ports', value: 'USB Type-C, 3.5mm Audio, Charging Pins' },
      { label: 'Wireless', value: 'Bluetooth 5.1 Low Latency' },
    ],
    colors: [
      { name: 'Cosmic Orchid', hex: '#a855f7', available: true },
      { name: 'White', hex: '#ffffff', available: true },
      { name: 'Midnight Black', hex: '#0f172a', available: true },
      { name: 'Volcanic Red', hex: '#dc2626', available: true },
      { name: 'Sterling Silver', hex: '#cbd5e1', available: true },
    ],
  },
  {
    id: 'charging-station',
    name: 'DualSense® Charging Station',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Charging & Docks',
    label: 'Setup Gear',
    price: 29.99,
    glyph: 'CHG',
    wash: 'hsl(240 65% 75% / .28)',
    badge: 'CLICK-IN DOCK',
    spec: 'Dual Fast-Charge Hub · USB-C Stand',
    rating: 4.93,
    reviewsCount: 1840,
    inStock: true,
    shortDesc: 'Charge up to two DualSense wireless controllers simultaneously without connecting them to your PS5 console.',
    fullDesc: 'Dock up to two DualSense or DualSense Edge wireless controllers quickly and easily with the charging station click-in design. Your controllers charge as quickly as when connected to your PS5 console — so you can free up USB ports without sacrificing charging speed.',
    features: [
      'Click-in design docks controllers securely and effortlessly',
      'Charges up to two controllers concurrently at maximum speed',
      'Frees up your PS5 console USB ports for external SSDs or headsets',
      'Matches the sleek, futuristic aesthetics of the PS5 family',
      'AC power adapter included in box for independent wall socket power',
    ],
    specs: [
      { label: 'Capacity', value: '2 Controllers Simultaneously' },
      { label: 'Power Input', value: '5V / 2.8A Dedicated AC Adapter' },
      { label: 'Charge Time', value: 'Approx. 2.5 Hours Full Depletion' },
      { label: 'Form Factor', value: 'Weighted Anti-Slip Base' },
    ],
  },
  {
    id: 'ps5-console-covers',
    name: 'PS5® Console Covers / Obsidian Void',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Custom Plates',
    label: 'Cosmetics',
    price: 54.99,
    glyph: 'PLATE',
    wash: 'hsl(265 70% 60% / .28)',
    badge: 'OBSIDIAN FINISH',
    spec: 'Precision Molded · Anti-Scratch Matte Finish',
    rating: 4.79,
    reviewsCount: 820,
    inStock: true,
    shortDesc: 'Transform your PS5 console setup with official matte obsidian faceplates designed for the new slim chassis.',
    fullDesc: 'Made by PlayStation: The only console covers made by PlayStation for PS5 that are delivered with the quality level you know and trust. Easy to install: Simply remove your original white PS5 console covers and click your new covers into place. Complete the look by pairing your new console covers with a matching DualSense wireless controller.',
    features: [
      'Official PlayStation manufactured precision fit with zero creaks or gaps',
      'Durable polycarbonate construction with scratch-resistant matte obsidian coating',
      'Optimized airflow intake ports ensure console stays whisper-quiet',
      'Available for both Disc and Digital PS5 Slim editions',
    ],
    specs: [
      { label: 'Material', value: 'Injection-Molded High-Grade Polycarbonate' },
      { label: 'Compatibility', value: 'PS5 Slim Disc & Digital Versions' },
      { label: 'Finish', value: 'Micro-Textured Anti-Fingerprint Matte' },
    ],
    colors: [
      { name: 'Midnight Black', hex: '#0f172a', available: true },
      { name: 'Chroma Indigo', hex: '#4338ca', available: true },
      { name: 'Sterling Silver', hex: '#cbd5e1', available: true },
    ],
  },
  {
    id: 'pulse-explore',
    name: 'PULSE Explore™ Wireless Earbuds',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Audio',
    label: 'Hi-Res Audio',
    price: 199.99,
    glyph: 'EARBUD',
    wash: 'hsl(280 80% 65% / .3)',
    badge: 'PLANAR EARBUD',
    spec: 'Planar Magnetic Drivers · AI Noise Rejection · Dual BT',
    rating: 4.81,
    reviewsCount: 910,
    inStock: true,
    shortDesc: 'Ultra-portable gaming earbuds with studio-grade planar magnetic sound and simultaneous multi-device audio.',
    fullDesc: 'Experience a new era in gaming audio at home and on the go with PULSE Explore wireless earbuds. Enjoy extraordinary lifelike sound with planar magnetic drivers, lightning-fast PlayStation Link lossless wireless connectivity, and AI-enhanced microphone noise rejection. Includes charging case providing up to 10 additional hours of battery.',
    features: [
      'Planar magnetic drivers in an ultra-compact earbud form factor',
      'PlayStation Link lossless wireless connection with zero perceptible latency',
      'Connect to your phone via Bluetooth while simultaneously playing on PS5',
      'AI microphone noise filtering trained to remove background fan and chewing noise',
      'Charging case with secure magnetic snap and USB-C quick charge',
    ],
    specs: [
      { label: 'Battery Life', value: '5h Earbuds + 10h Charging Case (15h Total)' },
      { label: 'Connectivity', value: 'PS Link 2.4GHz Dongle & Bluetooth 5.3' },
      { label: 'Ear Tips', value: '4 Pairs Included (XS, S, M, L Silicone)' },
    ],
  },
  {
    id: 'sn850p-ssd',
    name: 'WD_BLACK™ SN850P 2TB NVMe SSD for PS5',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Storage',
    label: 'High-Speed NVMe',
    price: 189.99,
    originalPrice: 229.99,
    glyph: '2TB SSD',
    wash: 'hsl(260 85% 65% / .3)',
    badge: 'OFFICIAL SONY LICENSED',
    spec: 'Up to 7,300 MB/s Read · Custom Engineered Heatsink',
    rating: 4.98,
    reviewsCount: 3600,
    inStock: true,
    shortDesc: 'Officially licensed M.2 SSD for PS5 consoles. Store and play games directly with speeds up to 7,300 MB/s.',
    fullDesc: 'Expand your PS5 console storage with the officially licensed WD_BLACK SN850P NVMe SSD. Featuring an exclusive custom-designed heatsink bearing the PlayStation logo, this drive installs in seconds into the internal M.2 expansion slot so you can store more titles with blistering read speeds up to 7,300 MB/s.',
    features: [
      'Officially tested and approved for Sony PlayStation 5 consoles',
      'All-in-one heatsink design crafted specifically for the PS5 M.2 bay',
      'Read speeds up to 7,300 MB/s and write speeds up to 6,600 MB/s',
      'Play PS5 and PS4 games directly without transferring back and forth',
      '5-Year Western Digital manufacturer limited warranty',
    ],
    specs: [
      { label: 'Capacity', value: '2,000GB (2TB High-Density 3D NAND)' },
      { label: 'Interface', value: 'PCIe Gen4 x4 NVMe 1.4' },
      { label: 'Form Factor', value: 'M.2 2280 with Pre-Installed Heatsink' },
      { label: 'Endurance', value: '1,200 TBW (Terabytes Written)' },
    ],
  },
];

export const GAMES: Product[] = [
  {
    id: 'astro-bot',
    name: 'Astro Bot',
    type: 'games',
    category: 'games',
    subCategory: 'Platformer',
    genre: ['3D Platformer', 'Adventure', 'Family', 'PlayStation Studios'],
    label: 'New Release',
    price: 59.99,
    glyph: 'ASTRO',
    wash: 'hsl(272 90% 68% / .32)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(272 90% 40% / .35), transparent 70%)',
    badge: 'GOTY 2024',
    metacritic: 94,
    esrb: 'EVERYONE 10+',
    releaseDate: 'September 6, 2024',
    publisher: 'Sony Interactive Entertainment',
    developer: 'Team ASOBI',
    spec: 'DualSense Enhanced · 4K 60FPS · 3D Audio',
    rating: 4.98,
    reviewsCount: 4150,
    inStock: true,
    shortDesc: 'Join ASTRO in a brand-new supersized space adventure across 50+ diverse planets packed with iconic PlayStation cameos.',
    fullDesc: 'The PS5 mothership has been wrecked, leaving ASTRO and the bot crew scattered across galaxies. Ride your trusty DualSpeeder across more than 50 planets full of fun, danger, and surprises. On your journey, make the most of ASTRO new powers and reunite with dozens of iconic heroes from the PlayStation universe!',
    features: [
      'Over 50 vibrant galaxies featuring volcanic planets, lush jungles, and cosmic void zones',
      '15+ new abilities taking full advantage of the DualSense adaptive triggers and haptics',
      'Rescue over 300 VIP bots styled as legendary PlayStation characters',
      'Flawless native 4K presentation running locked at 60 frames per second',
      'Tempest 3D Audio immersion lets you hear every rustle, splash, and robotic footstep',
    ],
    specs: [
      { label: 'Platform', value: 'PlayStation 5 (PS5 Pro Enhanced)' },
      { label: 'Resolution', value: 'Dynamic 4K @ 60 FPS' },
      { label: 'DualSense Support', value: 'Full Haptic Feedback & Adaptive Triggers' },
      { label: 'Audio', value: 'Tempest 3D AudioTech Supported' },
      { label: 'Storage Required', value: '66 GB Ultra-Fast SSD' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Edition',
        price: 59.99,
        perks: ['Full ASTRO BOT Game', 'Parappa the Rapper Lovestruck Outfit (Unlockable)', 'DualSpeeder Glorious Graffiti Paint'],
      },
      {
        id: 'digital-deluxe',
        name: 'Digital Deluxe Edition',
        price: 69.99,
        perks: [
          'Full ASTRO BOT Game',
          'ASTRO Yharnam Hunter Outfit (Bloodborne homage)',
          'ASTRO Golden Outfit',
          'Neon Dream DualSpeeder Color',
          'Champions' + ' Golden DualSpeeder Color',
          '10 PSN Avatars',
          'Digital Soundtrack and Art Gallery',
        ],
      },
    ],
    enhancements: ['PS5 Pro Enhanced', 'Full DualSense Haptics', '60 FPS Fidelity', '3D Audio'],
  },
  {
    id: 'elden-ring',
    name: 'Elden Ring: Shadow of the Erdtree Edition',
    type: 'games',
    category: 'games',
    subCategory: 'Action RPG',
    genre: ['Action RPG', 'Open World', 'Dark Fantasy', 'Souls-like'],
    label: 'RPG',
    price: 69.99,
    originalPrice: 79.99,
    glyph: 'ER',
    wash: 'hsl(270 50% 55% / .32)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(35 80% 40% / .3), transparent 70%)',
    badge: 'SHADOW DLC INCLUDED',
    metacritic: 95,
    esrb: 'MATURE 17+',
    releaseDate: 'June 21, 2024',
    publisher: 'FromSoftware / Bandai Namco',
    developer: 'FromSoftware Inc.',
    spec: 'Shadow of the Erdtree DLC · Ray Tracing Mode · HDR',
    rating: 4.96,
    reviewsCount: 8920,
    inStock: true,
    shortDesc: 'The critically acclaimed Game of the Year together with the massive expansion Shadow of the Erdtree in one ultimate collection.',
    fullDesc: 'Guided by Empyrean Miquella, players are summoned to the Land of Shadow, a place obscured by the Erdtree where the goddess Marika first set foot. In these strange new lands, uncover the dark secrets of the world as you meet others who follow in Miquella footsteps with ulterior motives.',
    features: [
      'Includes the complete ELDEN RING base game plus the critically lauded Shadow of the Erdtree expansion',
      'Explore the breathtaking Land of Shadow: vertically stacked catacombs, ancient keeps, and celestial plateaus',
      'Over 100 new weapons across 8 entirely new weapon categories including Hand-to-Hand Martial Arts and Light Greatswords',
      'Devastating new sorceries, incantations, spirit ashes, and legendary talismans',
      'Challenging epic multi-phase boss encounters with grand orchestral compositions',
    ],
    specs: [
      { label: 'Visual Modes', value: 'Performance (60FPS) or Quality (4K Ray Tracing)' },
      { label: 'Multiplayer', value: '1-3 Players Co-op & Competitive Invasions' },
      { label: 'Storage Required', value: '80 GB High-Speed SSD' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Shadow of the Erdtree Edition',
        price: 69.99,
        perks: ['ELDEN RING Base Game', 'Shadow of the Erdtree Expansion Voucher'],
      },
      {
        id: 'deluxe',
        name: 'Deluxe Edition',
        price: 99.99,
        perks: [
          'ELDEN RING Base Game',
          'Shadow of the Erdtree Expansion Voucher',
          'Digital Artbook & Original Soundtrack (Base + Expansion)',
          'Bonus Gesture: Ring of Miquella',
        ],
      },
    ],
    enhancements: ['HDR Supported', 'Ray Tracing', 'DualSense Trigger Effects', 'Ultra-Fast Loading'],
  },
  {
    id: 'spider-man',
    name: 'Marvel’s Spider-Man 2',
    type: 'games',
    category: 'games',
    subCategory: 'Action Adventure',
    genre: ['Superhero', 'Action Adventure', 'Open World', 'PlayStation Studios'],
    label: 'PS5 Exclusive',
    price: 69.99,
    glyph: 'SM2',
    wash: 'hsl(275 92% 70% / .32)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(350 85% 45% / .3), transparent 70%)',
    badge: 'PS5 EXCLUSIVE',
    metacritic: 90,
    esrb: 'TEEN',
    releaseDate: 'October 20, 2023',
    publisher: 'Sony Interactive Entertainment',
    developer: 'Insomniac Games',
    spec: 'Instant Fast-Travel · 3D Audio · Ray-Traced City',
    rating: 4.91,
    reviewsCount: 6240,
    inStock: true,
    shortDesc: 'Spider-Men Peter Parker and Miles Morales return for an exciting new adventure in the critically acclaimed Marvel’s Spider-Man franchise.',
    fullDesc: 'Swing, jump, and utilize the new Web Wings to travel across Marvel’s New York, quickly switching between Peter Parker and Miles Morales to experience different stories and epic new powers, as the iconic villain Venom threatens to destroy their lives, their city, and the ones they love.',
    features: [
      'Near-instantaneous switching between Peter Parker and Miles Morales across an expanded NYC',
      'Unleash the brutal power of the Symbiote alongside Miles bio-electric venom blasts',
      'Battle a rogue gallery of Marvel Super Villains: Venom, Kraven the Hunter, the Lizard, and more',
      'Web Wings allow high-speed gliding through urban wind tunnels across Queens and Brooklyn',
      'Ray-traced reflections enabled across every visual mode including 30, 40, and 60 FPS VRR',
    ],
    specs: [
      { label: 'Platform', value: 'PS5 & PS5 Pro Enhanced' },
      { label: 'VRR Support', value: '120Hz Displays Supported (40 FPS & Unlocked Modes)' },
      { label: 'Ray Tracing', value: 'Always-On Ray-Traced Reflections and Ambient Shadows' },
      { label: 'Storage', value: '98 GB Ultra-High Speed SSD' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Edition',
        price: 69.99,
        perks: ['Full Game', 'Pre-order suit unlocks included in progression'],
      },
      {
        id: 'digital-deluxe',
        name: 'Digital Deluxe Edition',
        price: 79.99,
        perks: [
          'Full Game',
          '10 Exclusive Suits (5 for Peter, 5 for Miles)',
          'Additional Photo Mode items',
          '+5 Skill Points immediately unlocked',
        ],
      },
    ],
    enhancements: ['PS5 Pro Enhanced', 'Ray Tracing in All Modes', 'VRR 120Hz', 'Instant Fast Travel'],
  },
  {
    id: 'ghost-of-yotei',
    name: 'Ghost of Yōtei',
    type: 'games',
    category: 'games',
    subCategory: 'Action RPG',
    genre: ['Historical Action', 'Open World', 'Samurai', 'PlayStation Studios'],
    label: 'Upcoming Blockbuster',
    price: 69.99,
    glyph: 'YOTEI',
    wash: 'hsl(15 85% 60% / .32)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(15 85% 45% / .35), transparent 70%)',
    badge: 'PRE-ORDER NOW',
    metacritic: 96,
    esrb: 'MATURE 17+',
    releaseDate: 'Expected 2025',
    publisher: 'Sony Interactive Entertainment',
    developer: 'Sucker Punch Productions',
    spec: 'Sucker Punch Production · Mount Yōtei Era · Dual Blades',
    rating: 4.97,
    reviewsCount: 1540,
    inStock: true,
    shortDesc: 'A brand-new protagonist, Atsu, journeys across the harsh wilderness surrounding Mount Yōtei in 1603 Japan.',
    fullDesc: 'Set 300 years after Ghost of Tsushima, Ghost of Yōtei takes players to the lands surrounding Mount Yōtei, a towering peak in the heart of Ezo (modern-day Hokkaido). Experience a gripping tale of an underdog mercenary wielding new weaponry including firearms, dual katanas, and kusarigama in an untamed frontier beyond Japanese clan rule.',
    features: [
      'Expansive dynamic wilderness featuring seasonal snowfall, auroras, and untamed wildlife',
      'Dual katana mastery, rifle marksmanship, and stealth grappling combat arts',
      'Cinematic Kurosawa and contemporary Japanese film presentation modes',
      'Deeply personal revenge saga with non-linear frontier bounty hunting',
      'Built from the ground up to exploit the full power of PS5 and PS5 Pro',
    ],
    specs: [
      { label: 'Platform', value: 'PS5 & PS5 Pro Exclusive' },
      { label: 'Audio', value: 'Binaural Traditional Japanese Instrumentation & 3D Tempest' },
      { label: 'Display', value: 'Target 4K 60FPS Fidelity Mode' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Pre-Order',
        price: 69.99,
        perks: ['Full Game', 'In-Game Ronin Dye: Red Maple', 'Ghost Horse Saddle and Reins'],
      },
      {
        id: 'special-ronin',
        name: 'Special Ronin Edition',
        price: 89.99,
        perks: [
          'Full Game with 48h Early Access',
          'Digital Mini Artbook by Sucker Punch',
          'Yōtei Mask Replica Stand (DLC In-game cosmetic)',
          'Golden Kensei Armor & Dual Scabbards',
          'Dynamic PS5 Dashboard Theme and Avatars',
        ],
      },
    ],
    enhancements: ['PS5 Pro Native', 'Haptic Weather Effects', 'Zero-Load Transitions'],
  },
  {
    id: 'final-fantasy-vii-rebirth',
    name: 'Final Fantasy VII Rebirth',
    type: 'games',
    category: 'games',
    subCategory: 'Action RPG',
    genre: ['JRPG', 'Action RPG', 'Fantasy', 'Sci-Fi'],
    label: 'Award Winner',
    price: 69.99,
    glyph: 'FFVII',
    wash: 'hsl(175 80% 60% / .3)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(175 80% 40% / .3), transparent 70%)',
    badge: 'CRITICS CHOICE',
    metacritic: 92,
    esrb: 'TEEN',
    releaseDate: 'February 29, 2024',
    publisher: 'Square Enix',
    developer: 'Square Enix Creative Business Unit I',
    spec: 'Massive Seamless Planet · Synergy Attacks · Queen’s Blood',
    rating: 4.93,
    reviewsCount: 5120,
    inStock: true,
    shortDesc: 'Cloud, Barret, Tifa, Aerith and Red XIII escape Midgar to pursue Sephiroth across a sprawling, vibrant world.',
    fullDesc: 'Final Fantasy VII Rebirth is the highly anticipated second entry in the Final Fantasy VII remake project. After escaping the dystopian city of Midgar, Cloud and his friends embark on an overland journey across the planet. New adventures await in a vast and multifaceted world — sprint across grassy plains on a Chocobo and explore expansive environments.',
    features: [
      'Massive interconnected world spanning Kalm, Junon, Costa del Sol, Corel, and Cosmo Canyon',
      'Evolved active-time combat system featuring explosive dual-character Synergy Abilities',
      'The addictive in-world tactical card game Queen’s Blood with over 145 unique cards',
      'Chocobo breeding, racing, and customizable Gold Saucer amusement park minigames',
      'Deep, emotional narrative re-examining destiny, loss, and the fate of the Planet',
    ],
    specs: [
      { label: 'Discs', value: '2 Ultra-HD Blu-ray Discs (Disc Edition) or 150GB Download' },
      { label: 'Voice Acting', value: 'Full English and Japanese Voice Options' },
      { label: 'Audio', value: 'Over 400 Newly Arranged Musical Tracks' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Edition',
        price: 69.99,
        perks: ['Full Final Fantasy VII Rebirth Game (2 Discs / 150GB)'],
      },
      {
        id: 'deluxe',
        name: 'Digital Deluxe Edition',
        price: 89.99,
        perks: [
          'Full Game',
          'Digital Mini Soundtrack',
          'Digital Art Book',
          'Magic Pot Summoning Materia',
          'Reclaimant Choker Accessory',
          'Orchid Bracelet Armor',
        ],
      },
    ],
    enhancements: ['PS5 Pro Enhanced Mode', 'Dynamic Resolution 60FPS', 'DualSense Trigger Resistance'],
  },
  {
    id: 'helldivers-2',
    name: 'Helldivers 2',
    type: 'games',
    category: 'games',
    subCategory: 'Co-op Shooter',
    genre: ['Third-Person Shooter', 'Co-op', 'Sci-Fi Action'],
    label: 'Online Hit',
    price: 39.99,
    glyph: 'HD2',
    wash: 'hsl(45 90% 60% / .3)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(45 90% 45% / .3), transparent 70%)',
    badge: 'CO-OP SENSATION',
    metacritic: 82,
    esrb: 'MATURE 17+',
    releaseDate: 'February 8, 2024',
    publisher: 'Sony Interactive Entertainment',
    developer: 'Arrowhead Game Studios',
    spec: 'Galactic War Metagame · Crossplay · Stratagem Haptics',
    rating: 4.87,
    reviewsCount: 12400,
    inStock: true,
    shortDesc: 'Join the Helldivers and fight for freedom with friends across a hostile galaxy in this frantic third-person squad shooter.',
    fullDesc: 'Enlist in the Helldivers and fight for Managed Democracy! As an elite class of soldiers whose mission is to achieve peace, freedom, and liberty using the biggest, baddest and most explosive tools in the galaxy. Team up with up to four friends and wreak havoc on alien scourges that threaten Super Earth.',
    features: [
      'Cooperative 4-player tactical squad action with hilarious friendly fire chaos',
      'Call down explosive Stratagems: 500kg bombs, orbital lasers, and heavy mechs',
      'Living galaxy-wide metagame: every completed mission liberates planets in real time',
      'Full cross-play with PC players with seamless voice and ping systems',
    ],
    specs: [
      { label: 'Online Required', value: 'PlayStation Plus & Constant Network Connection' },
      { label: 'Party Size', value: '1 to 4 Players Co-op Squad' },
      { label: 'Storage', value: '45 GB High-Speed SSD' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Edition',
        price: 39.99,
        perks: ['Full Helldivers 2 Game', 'Access to all free Galactic War updates'],
      },
      {
        id: 'super-citizen',
        name: 'Super Citizen Edition',
        price: 59.99,
        perks: [
          'Full Helldivers 2 Game',
          'DP-53 Savior of the Free Armor Set',
          'Will of the People Cape',
          'MP-98 Knight Submachine Gun',
          'Super Citizen Status Title',
          'Stratagem Hero Ship Game',
          'Steeled Veterans Premium Warbond Access',
        ],
      },
    ],
    enhancements: ['Adaptive Triggers for Weapon Kickback', '60 FPS Performance Mode', 'Cross-Platform Play'],
  },
  {
    id: 'silent-hill-2',
    name: 'Silent Hill 2 Remake',
    type: 'games',
    category: 'games',
    subCategory: 'Psychological Horror',
    genre: ['Survival Horror', 'Psychological Horror', 'Mystery'],
    label: 'Remake',
    price: 69.99,
    glyph: 'SH2',
    wash: 'hsl(0 60% 50% / .3)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(0 60% 35% / .3), transparent 70%)',
    badge: 'UNREAL ENGINE 5',
    metacritic: 86,
    esrb: 'MATURE 17+',
    releaseDate: 'October 8, 2024',
    publisher: 'KONAMI',
    developer: 'Bloober Team',
    spec: 'Unreal Engine 5 · Over-the-Shoulder Camera · 3D Audio',
    rating: 4.86,
    reviewsCount: 2900,
    inStock: true,
    shortDesc: 'Having received a letter from his deceased wife, James heads to where they shared so many memories: the fog-draped town of Silent Hill.',
    fullDesc: 'Experience a masterclass in psychological survival horror lauded as the best in the series on the latest hardware with chilling visuals and visceral sounds. Explore sinister locations with an over-the-shoulder perspective, modern combat mechanics, and stunning ray-traced fog volumetric effects powered by Unreal Engine 5.',
    features: [
      'Rebuilt from the ground up with cutting-edge Unreal Engine 5 visuals and Lumen lighting',
      'Modernized over-the-shoulder camera for intense close-quarters tension',
      'DualSense radio static sounds emit directly from the controller speaker as creatures approach',
      'Extended and reimagined town areas including new interior buildings and puzzles',
      'Haunting legendary soundtrack fully rescored by Akira Yamaoka',
    ],
    specs: [
      { label: 'Engine', value: 'Unreal Engine 5 (Lumen Global Illumination)' },
      { label: 'Controller Feature', value: 'Radio Static emitted through DualSense Speaker' },
      { label: 'Storage', value: '52 GB High-Speed SSD' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Edition',
        price: 69.99,
        perks: ['Full Silent Hill 2 Game'],
      },
      {
        id: 'deluxe',
        name: 'Digital Deluxe Edition',
        price: 79.99,
        perks: [
          'Full Game',
          'Digital Artbook featuring original concept sketches',
          'Digital Soundtrack by Akira Yamaoka',
          'Pyramid Head Mask (Pizza Box) cosmetic',
          'Robbie the Rabbit Mask (PS5 Exclusive)',
        ],
      },
    ],
    enhancements: ['PS5 Pro Enhanced', '3D Tempest Audio', 'Haptic Heartbeat Feedback'],
  },
  {
    id: 'death-stranding-2',
    name: 'Death Stranding 2: On The Beach',
    type: 'games',
    category: 'games',
    subCategory: 'Sci-Fi Adventure',
    genre: ['Cinematic Adventure', 'Sci-Fi', 'Action', 'PlayStation Studios'],
    label: 'Kojima Masterpiece',
    price: 69.99,
    glyph: 'DS2',
    wash: 'hsl(215 80% 60% / .3)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(215 80% 40% / .35), transparent 70%)',
    badge: 'COMING 2025',
    metacritic: 93,
    esrb: 'MATURE 17+',
    releaseDate: 'Expected 2025',
    publisher: 'Sony Interactive Entertainment',
    developer: 'KOJIMA PRODUCTIONS',
    spec: 'Decima Engine · Norman Reedus · Cinematic Odyssey',
    rating: 4.95,
    reviewsCount: 1880,
    inStock: true,
    shortDesc: 'Embark on an inspiring mission of human connection beyond the UCA. Sam with companions sets out on a new journey to save humanity from extinction.',
    fullDesc: 'From legendary game creator Hideo Kojima comes Death Stranding 2: On The Beach. Sam Porter Bridges returns alongside Fragile, aboard the automated ship DHV Magellan, navigating unpredictable environmental hazards like earthquakes, forest fires, and torrential mudslides in an untamed continent.',
    features: [
      'Groundbreaking real-time terrain shifts, flash floods, and natural catastrophe mechanics',
      'Expanded combat and stealth capabilities with modular robotic transport systems',
      'All-star cinematic cast including Norman Reedus, Léa Seydoux, Elle Fanning, and Shioli Kutsuna',
      'Powered by Guerrilla Games state-of-the-art Decima Engine',
      'Philosophical exploration: "Should we have connected?"',
    ],
    specs: [
      { label: 'Platform', value: 'PlayStation 5 & PS5 Pro Exclusive' },
      { label: 'Technology', value: 'Decima Engine with Photogrammetry Assets' },
      { label: 'DualSense', value: 'Terrain Texture Surface Feedback & Water Resistance Triggers' },
    ],
    editions: [
      {
        id: 'standard',
        name: 'Standard Pre-Order',
        price: 69.99,
        perks: ['Full Game', 'DHV Magellan Patch (In-Game Outfit)', 'Gold Exoskeleton Framework'],
      },
      {
        id: 'strand-collector',
        name: 'Strand Collector Edition',
        price: 89.99,
        perks: [
          'Full Game with Early Access',
          'Digital Original Soundtrack & Audio Commentary',
          'Exclusive "Drawbridge" Ship Custom Decals',
          'Chiral Crystal Suit Variant for Sam',
        ],
      },
    ],
    enhancements: ['Decima Engine Next-Gen', 'Ultra-Fast SSD Streaming', '4K 60FPS Fidelity'],
  },
];

export const GAMES_STOREFRONT: Product[] = [
  {
    id: 'elden-ring',
    name: 'Elden Ring Shadow of the Erdtree',
    type: 'games',
    category: 'games',
    subCategory: 'Action RPG',
    genre: ['Action', 'RPG', 'Adventure'],
    label: 'RPG',
    price: 4999,
    glyph: 'ER',
    wash: 'hsl(270 50% 55% / .32)',
    backdropWash: 'radial-gradient(ellipse at 50% 30%, hsl(35 80% 40% / .3), transparent 70%)',
    badge: 'SHADOW DLC INCLUDED',
    discountBadge: 'NEW',
    platform: 'pc',
    coverImage: '/covers/elden-ring.jpg',
    rating: 4.96,
    reviewsCount: 8920,
    inStock: true,
    shortDesc: 'A new realm awaits. Journey deeper into the Lands Between with Miquella in the acclaimed expansion.',
    fullDesc: 'Guided by Empyrean Miquella, players are summoned to the Land of Shadow, a place obscured by the Erdtree where the goddess Marika first set foot. In these strange new lands, uncover the dark secrets of the world as you meet others who follow in Miquella footsteps with ulterior motives.',
    features: [
      'Complete ELDEN RING base game experience plus the monumental Shadow of the Erdtree expansion',
      'Over 100 new weapons, spells, and talismans across 8 new weapon classes',
      'Stunning dark fantasy vertical world design with subterranean ruins and towering keeps',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam) & PS5' },
      { label: 'Storage', value: '80 GB SSD Required' },
    ],
  },
  {
    id: 'wukong',
    name: 'Black Myth: Wukong',
    type: 'games',
    category: 'games',
    subCategory: 'Action RPG',
    genre: ['Action', 'RPG', 'Adventure'],
    label: 'Action RPG',
    price: 3599,
    originalPrice: 4500,
    glyph: 'BMW',
    wash: 'hsl(35 70% 50% / .3)',
    discountBadge: '-20%',
    platform: 'pc',
    coverImage: '/covers/wukong.jpg',
    rating: 4.91,
    reviewsCount: 14200,
    inStock: true,
    shortDesc: 'Embark as the Destined One through Chinese mythology to uncover the obscured truth of a glorious past.',
    fullDesc: 'Black Myth: Wukong is an action RPG rooted in Chinese mythology. The story is based on Journey to the West, one of the Four Great Classical Novels of Chinese literature. You shall set out as the Destined One to venture into the challenges and marvels ahead, to uncover the obscured truth beneath the veil of a glorious legend from the past.',
    features: [
      'Master the staff combat techniques and mythological spells of Sun Wukong',
      'Unreal Engine 5 graphical fidelity with full path tracing and Nanite foliage',
      'Dozens of unique mythical boss encounters inspired by classical Chinese folklore',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Engine', value: 'Unreal Engine 5' },
    ],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    type: 'games',
    category: 'games',
    subCategory: 'Open World RPG',
    genre: ['Action', 'RPG', 'Shooter'],
    label: 'Open World',
    price: 2999,
    originalPrice: 4500,
    glyph: 'CP77',
    wash: 'hsl(55 90% 50% / .3)',
    discountBadge: '-33%',
    platform: 'pc',
    coverImage: '/covers/cyberpunk.jpg',
    rating: 4.88,
    reviewsCount: 19800,
    inStock: true,
    shortDesc: 'An open-world, action-adventure RPG set in the megalopolis of Night City, where power and body modification reign.',
    fullDesc: 'Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Upgraded with the 2.0 update and full ray tracing overdrive.',
    features: [
      'Breathtaking futuristic open-world Night City with vertical exploration',
      'Deep cyberware customization, perks overhaul, and vehicular combat',
      'Keanu Reeves as legendary rockerboy Johnny Silverhand',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Ray Tracing', value: 'Full Path Tracing Overdrive' },
    ],
  },
  {
    id: 'gta5',
    name: 'Grand Theft Auto V',
    type: 'games',
    category: 'games',
    subCategory: 'Open World Action',
    genre: ['Action', 'Adventure'],
    label: 'Open World',
    price: 2499,
    glyph: 'GTAV',
    wash: 'hsl(140 60% 45% / .3)',
    platform: 'pc',
    coverImage: '/covers/gta5.jpg',
    rating: 4.94,
    reviewsCount: 45000,
    inStock: true,
    shortDesc: 'When a young street hustler, a retired bank robber and a terrifying psychopath find themselves entangled with the criminal underworld.',
    fullDesc: 'Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.',
    features: [
      'Three interconnected playable protagonists: Michael, Franklin, and Trevor',
      'Includes access to Grand Theft Auto Online with continuous content updates',
      'Rockstar Editor for recording and creating custom cinematic gameplay clips',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Resolution', value: '4K Ultra-Wide Support' },
    ],
  },
  {
    id: 'rdr2',
    name: 'Red Dead Redemption 2',
    type: 'games',
    category: 'games',
    subCategory: 'Open World Epic',
    genre: ['Action', 'Adventure'],
    label: 'Epic Masterpiece',
    price: 3999,
    glyph: 'RDR2',
    wash: 'hsl(0 75% 50% / .3)',
    platform: 'pc',
    coverImage: '/covers/rdr2.jpg',
    rating: 4.97,
    reviewsCount: 32000,
    inStock: true,
    shortDesc: 'Winner of over 175 Game of the Year Awards. The epic tale of outlaw Arthur Morgan and the Van der Linde gang on the run across America.',
    fullDesc: 'America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.',
    features: [
      'Unrivaled narrative depth and living, breathing open-world ecosystem',
      'Deep hunting, fishing, horse bonding, and survival mechanics',
      'Free access to Red Dead Online multiplayer frontier',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Audio', value: 'Dolby Atmos Spatial Audio' },
    ],
  },
  {
    id: 'hogwarts',
    name: 'Hogwarts Legacy',
    type: 'games',
    category: 'games',
    subCategory: 'Open World RPG',
    genre: ['Action', 'Adventure', 'RPG'],
    label: 'Wizarding World',
    price: 3499,
    glyph: 'HL',
    wash: 'hsl(210 60% 50% / .3)',
    platform: 'pc',
    coverImage: '/covers/hogwarts.jpg',
    rating: 4.89,
    reviewsCount: 16500,
    inStock: true,
    shortDesc: 'Experience Hogwarts in the 1800s. Your character is a student who holds the key to an ancient secret that threatens the wizarding world.',
    fullDesc: 'Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Now you can take control of the action and be at the center of your own adventure in the wizarding world.',
    features: [
      'Freely roam Hogwarts Castle, Hogsmeade, the Forbidden Forest, and surrounding Overland area',
      'Cast spells, brew potions, grow plants, and tend magical beasts along your journey',
      'Get sorted into your house, forge relationships, and master skills to become the witch or wizard you want to be',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Visuals', value: 'Ray Traced Reflections and Shadows' },
    ],
  },
  {
    id: 'tlou1',
    name: 'The Last of Us Part I',
    type: 'games',
    category: 'games',
    subCategory: 'Action Adventure',
    genre: ['Action', 'Adventure'],
    label: 'Story-Rich',
    price: 2399,
    originalPrice: 3999,
    glyph: 'TLOU',
    wash: 'hsl(25 80% 50% / .3)',
    discountBadge: '-40%',
    platform: 'playstation',
    coverImage: '/covers/tlou1.jpg',
    rating: 4.95,
    reviewsCount: 11200,
    inStock: true,
    shortDesc: 'Experience the emotional storytelling and unforgettable characters in The Last of Us, rebuilt for PlayStation 5.',
    fullDesc: 'In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey.',
    features: [
      'Completely rebuilt from the ground up utilizing Naughty Dog PS5 engine technology',
      'Modernized gameplay mechanics, improved controls, and expanded accessibility options',
      'Includes the complete single-player story and celebrated prequel chapter Left Behind',
    ],
    specs: [
      { label: 'Platform', value: 'PlayStation 5' },
      { label: 'Haptics', value: 'Full DualSense Haptic Feedback' },
    ],
  },
  {
    id: 'gow-ragnarok',
    name: 'God of War Ragnarök',
    type: 'games',
    category: 'games',
    subCategory: 'Action Adventure',
    genre: ['Action', 'Adventure', 'RPG'],
    label: 'Blockbuster',
    price: 3749,
    originalPrice: 4999,
    glyph: 'GOW',
    wash: 'hsl(215 80% 55% / .3)',
    discountBadge: '-25%',
    platform: 'playstation',
    coverImage: '/covers/gow-ragnarok.jpg',
    rating: 4.98,
    reviewsCount: 22400,
    inStock: true,
    shortDesc: 'Kratos and Atreus embark on a mythic journey for answers before the prophesied battle that will end the Nine Realms.',
    fullDesc: 'From Santa Monica Studio comes the sequel to the critically acclaimed God of War (2018). Fimbulwinter is well underway. Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.',
    features: [
      'Journey through all Nine Realms of Norse mythology across gorgeous, lethal environments',
      'Dual wielding Leviathan Axe, Blades of Chaos, and the versatile Draupnir Spear',
      'Includes free roguelite expansion God of War Ragnarök: Valhalla',
    ],
    specs: [
      { label: 'Platform', value: 'PlayStation 5' },
      { label: 'Frame Rate', value: 'Target 60 FPS / High Frame Rate Mode' },
    ],
  },
  {
    id: 'fc24',
    name: 'EA SPORTS FC 24',
    type: 'games',
    category: 'games',
    subCategory: 'Sports Simulation',
    genre: ['Simulation', 'Strategy'],
    label: 'Sports',
    price: 2499,
    originalPrice: 4999,
    glyph: 'FC24',
    wash: 'hsl(190 85% 50% / .3)',
    discountBadge: '-50%',
    platform: 'pc',
    coverImage: '/covers/fc24.jpg',
    rating: 4.65,
    reviewsCount: 18200,
    inStock: true,
    shortDesc: 'A new era for The World’s Game. 19,000+ fully licensed players, 700+ teams, and 30+ leagues playing together.',
    fullDesc: 'EA SPORTS FC™ 24 brings you closer to the football than ever before, powered by a trinity of technologies driving gameplay realism in every match: HyperMotionV, PlayStyles optimized by Opta, and a revolutionized Frostbite™ Engine.',
    features: [
      'HyperMotionV captures the game as it is truly played using volumetric data from 180+ pro matches',
      'PlayStyles dimensionalize athletes, interpreting data from Opta to bring unique realism',
      'Build your dream squad in Ultimate Team with men and women playing on the same pitch',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Players', value: '1-4 Local / 22 Online' },
    ],
  },
  {
    id: 'forza5',
    name: 'Forza Horizon 5',
    type: 'games',
    category: 'games',
    subCategory: 'Racing Simulation',
    genre: ['Racing', 'Simulation'],
    label: 'Open World Racing',
    price: 3999,
    glyph: 'FH5',
    wash: 'hsl(15 90% 55% / .3)',
    platform: 'xbox',
    coverImage: '/covers/forza5.jpg',
    rating: 4.93,
    reviewsCount: 15600,
    inStock: true,
    shortDesc: 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico.',
    fullDesc: 'Lead breathtaking expeditions across the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.',
    features: [
      'Vast, diverse open world map including living deserts, lush jungles, historic cities, and a towering volcano',
      'Over 500 licensed authentic vehicles with deep customization and tuning options',
      'EventLab gameplay toolset lets you create custom races, stunts, challenges, and new game modes',
    ],
    specs: [
      { label: 'Platform', value: 'Xbox One / Series X|S & PC' },
      { label: 'Resolution', value: 'Native 4K HDR 60 FPS' },
    ],
  },
  {
    id: 're4-remake',
    name: 'Resident Evil 4 Remake',
    type: 'games',
    category: 'games',
    subCategory: 'Survival Horror',
    genre: ['Action', 'Shooter'],
    label: 'Survival Horror',
    price: 3149,
    originalPrice: 4500,
    glyph: 'RE4',
    wash: 'hsl(340 70% 50% / .3)',
    discountBadge: '-30%',
    platform: 'pc',
    coverImage: '/covers/re4-remake.jpg',
    rating: 4.96,
    reviewsCount: 17800,
    inStock: true,
    shortDesc: 'Survival is only the beginning. Reimagined modern gameplay, a reimagined storyline, and vividly detailed graphics.',
    fullDesc: 'Six years have passed since the biological disaster in Raccoon City. Leon S. Kennedy, one of the survivors, has been sent to rescue the president kidnapped daughter from a secluded European village where something is terribly wrong with the locals.',
    features: [
      'Preserves the essence of the original masterpiece while introducing modernized mechanics',
      'Knife parry mechanics, stealth maneuvering, and tactile combat responsiveness',
      'Built in Capcom proprietary RE Engine with jaw-dropping photorealistic visuals',
    ],
    specs: [
      { label: 'Platform', value: 'PC (Steam)' },
      { label: 'Ray Tracing', value: 'RE Engine DXR Supported' },
    ],
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    type: 'games',
    category: 'games',
    subCategory: 'Sandbox Adventure',
    genre: ['Adventure', 'Simulation', 'Strategy'],
    label: 'Sandbox',
    price: 2199,
    glyph: 'MC',
    wash: 'hsl(110 60% 45% / .3)',
    platform: 'nintendo',
    coverImage: '/covers/minecraft.jpg',
    rating: 4.95,
    reviewsCount: 58000,
    inStock: true,
    shortDesc: 'Build, explore and survive in an infinite blocky world. Craft tools, mine resources, and build whatever you imagine.',
    fullDesc: 'Prepare for an adventure of limitless possibilities as you build, mine, battle mobs, and explore the ever-changing Minecraft landscape. Play with friends across platforms via cross-play.',
    features: [
      'Endless creative freedom in Creative Mode with unlimited building resources',
      'Challenging Survival Mode: craft weapons and armor to fend off dangerous mobs',
      'Cross-platform multiplayer play across console, mobile, and PC',
    ],
    specs: [
      { label: 'Platform', value: 'Nintendo Switch & Multi-Platform' },
      { label: 'Multiplayer', value: 'Cross-Platform Realms & Local Splitscreen' },
    ],
  },
];

export const ACCESSORIES_STOREFRONT: Product[] = [
  {
    id: 'dualsense-edge',
    name: 'DualSense Edge™ Wireless Controller',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Pro Controller',
    price: 24999,
    originalPrice: 27999,
    glyph: 'EDGE',
    wash: 'hsl(285 85% 72% / .32)',
    discountBadge: 'PRO',
    platform: 'playstation',
    coverImage: '/accessories/dualsense-edge.jpg',
    rating: 4.95,
    reviewsCount: 2450,
    inStock: true,
    shortDesc: 'Ultra-customizable pro controller built for high-performance esports with remappable back buttons and swappable modules.',
    fullDesc: 'Gain an edge in gameplay by crafting your own custom controls to fit your playstyle. Built with high performance and personalization in mind, the DualSense Edge wireless controller invites you to craft your own unique gaming experience so you can play your way.',
    features: [
      'Ultra-customizable controls with dedicated Fn buttons to quickly swap profiles',
      'Changeable stick caps and replaceable stick modules for longevity',
      'Configurable back buttons (half-dome and lever options included)',
    ],
    specs: [
      { label: 'Connectivity', value: 'Bluetooth 5.1 & Low-Latency USB-C' },
      { label: 'Weight', value: '325g (Counter-Weighted)' },
    ],
  },
  {
    id: 'pulse-elite',
    name: 'PULSE Elite™ Wireless Headset',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Audio & Headsets',
    label: 'Planar Magnetic Headset',
    price: 18999,
    originalPrice: 21999,
    glyph: 'ELITE',
    wash: 'hsl(272 90% 68% / .32)',
    discountBadge: '-15%',
    platform: 'playstation',
    coverImage: '/accessories/pulse-elite.jpg',
    rating: 4.92,
    reviewsCount: 1280,
    inStock: true,
    shortDesc: 'Next-generation planar magnetic drivers deliver studio-grade acoustics and ultra-low latency PlayStation Link wireless audio.',
    fullDesc: 'Experience extraordinarily lifelike audio in your favorite games with planar magnetic drivers, and hear every sound with lightning-fast PlayStation Link lossless wireless connectivity.',
    features: [
      'Planar Magnetic Drivers reproducing acoustic soundscapes with ultra-low distortion',
      'PlayStation Link™ lossless 2.4GHz wireless audio',
      'AI-enhanced noise rejection with retractable beamforming mic',
    ],
    specs: [
      { label: 'Driver Type', value: 'Custom Planar Magnetic' },
      { label: 'Battery', value: 'Up to 30 Hours' },
    ],
  },
  {
    id: 'dualsense-cosmic',
    name: 'DualSense® Wireless Controller - Galactic Purple',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Wireless Controller',
    price: 8499,
    glyph: 'DS-P',
    wash: 'hsl(285 85% 72% / .3)',
    discountBadge: 'NEW',
    platform: 'playstation',
    coverImage: '/accessories/dualsense-cosmic.jpg',
    rating: 4.9,
    reviewsCount: 3820,
    inStock: true,
    shortDesc: 'Feel your in-game actions and environment simulated through immersive haptic feedback in a celestial Galactic Purple finish.',
    fullDesc: 'Discover a deeper gaming experience with the innovative PS5 controller in Galactic Purple, featuring haptic feedback and dynamic triggers.',
    features: [
      'Immersive Haptic Feedback replaces traditional rumble motors',
      'Dynamic Adaptive Triggers simulate tension and resistance',
      'Galactic Purple premium cosmic finish',
    ],
    specs: [
      { label: 'Connectivity', value: 'Bluetooth 5.1 Low Latency' },
      { label: 'Battery', value: 'Rechargeable Lithium-Ion' },
    ],
  },
  {
    id: 'charging-station',
    name: 'DualSense® Charging Station',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Charging & Docks',
    label: 'Click-In Dock',
    price: 3499,
    glyph: 'CHG',
    wash: 'hsl(240 65% 75% / .28)',
    platform: 'playstation',
    coverImage: '/accessories/charging-station.jpg',
    rating: 4.93,
    reviewsCount: 1840,
    inStock: true,
    shortDesc: 'Charge up to two DualSense wireless controllers simultaneously without connecting them to your PS5 console.',
    fullDesc: 'Dock up to two DualSense or DualSense Edge wireless controllers quickly and easily with the charging station click-in design.',
    features: [
      'Click-in design docks controllers securely and effortlessly',
      'Charges up to two controllers concurrently at maximum speed',
      'Frees up your PS5 console USB ports',
    ],
    specs: [
      { label: 'Capacity', value: '2 Controllers Simultaneously' },
      { label: 'Power Input', value: 'Dedicated AC Adapter' },
    ],
  },
  {
    id: 'pulse-pro',
    name: 'Pulse 3D™ Wireless Headset - Midnight Black',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Audio & Headsets',
    label: 'Spatial Audio',
    price: 11499,
    originalPrice: 13999,
    glyph: 'PULSE',
    wash: 'hsl(245 75% 70% / .3)',
    discountBadge: '-20%',
    platform: 'playstation',
    coverImage: '/accessories/pulse-pro.jpg',
    rating: 4.82,
    reviewsCount: 3120,
    inStock: true,
    shortDesc: 'Fine-tuned specifically for 3D Audio on PS5 consoles. Features refined design with dual noise-cancelling microphones.',
    fullDesc: 'Play in comfort with a wireless headset fine-tuned for 3D Audio on PS5 consoles. Featuring USB Type-C charging and dual noise-cancelling microphones.',
    features: [
      'Engineered for 3D Audio on PS5 with custom equalizer presets',
      'Dual hidden microphones positioned for optimal clear voice capture',
      'Up to 12 hours of wireless play with the built-in rechargeable battery',
    ],
    specs: [
      { label: 'Compatibility', value: 'PS5, PS4, PC, Mac, PS VR2' },
      { label: 'Battery', value: '12 Hours Lithium-Ion USB-C' },
    ],
  },
  {
    id: 'ps5-console-covers',
    name: 'PS5® Console Covers / Obsidian Void',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Custom Plates',
    label: 'Faceplates',
    price: 6999,
    glyph: 'PLATE',
    wash: 'hsl(265 70% 60% / .28)',
    platform: 'playstation',
    coverImage: '/accessories/ps5-console-covers.jpg',
    rating: 4.79,
    reviewsCount: 820,
    inStock: true,
    shortDesc: 'Transform your PS5 console setup with official matte obsidian faceplates designed for the new slim chassis.',
    fullDesc: 'The only console covers made by PlayStation for PS5 that are delivered with the quality level you know and trust. Easy click-in installation.',
    features: [
      'Official PlayStation manufactured precision fit with zero creaks or gaps',
      'Durable polycarbonate construction with scratch-resistant matte obsidian coating',
      'Optimized airflow intake ports ensure console stays whisper-quiet',
    ],
    specs: [
      { label: 'Material', value: 'High-Grade Polycarbonate' },
      { label: 'Finish', value: 'Micro-Textured Anti-Fingerprint Matte' },
    ],
  },
  {
    id: 'xbox-elite-2',
    name: 'Xbox Elite Wireless Controller Series 2',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Pro Controller',
    price: 21999,
    originalPrice: 24500,
    glyph: 'XB-EL',
    wash: 'hsl(140 70% 45% / .3)',
    discountBadge: '-10%',
    platform: 'xbox',
    coverImage: '/accessories/xbox-elite-2.jpg',
    rating: 4.91,
    reviewsCount: 4200,
    inStock: true,
    shortDesc: 'Designed to meet the needs of today’s competitive gamers, featuring over 30 ways to play like a pro.',
    fullDesc: 'Experience the Xbox Elite Wireless Controller Series 2 featuring adjustable-tension thumbsticks, wrap-around rubberized grip, and shorter hair trigger locks.',
    features: [
      'Adjustable-tension thumbsticks and shorter hair trigger locks',
      'Interchangeable thumbsticks, paddle shapes, and D-pads',
      'Up to 40 hours of rechargeable battery life per charge',
    ],
    specs: [
      { label: 'Battery', value: '40 Hours Rechargeable' },
      { label: 'Platform', value: 'Xbox Series X|S, Xbox One, PC' },
    ],
  },
  {
    id: 'razer-viper-v3',
    name: 'Razer Viper V3 Pro Ultra-Lightweight Mouse',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Keyboards & Mice',
    label: 'Esports Mouse',
    price: 16999,
    glyph: 'VIPER',
    wash: 'hsl(120 70% 50% / .3)',
    discountBadge: 'NEW',
    platform: 'pc',
    coverImage: '/accessories/razer-viper-v3.jpg',
    rating: 4.96,
    reviewsCount: 1640,
    inStock: true,
    shortDesc: 'Hyper-speed wireless esports mouse engineered with pro players. Ultralight 54g design with Gen-2 Optical Switches.',
    fullDesc: 'Engineered in partnership with top esports pros, the Razer Viper V3 Pro features true 8000 Hz wireless polling rate and the world class Focus Pro 35K optical sensor.',
    features: [
      'Ultra-lightweight 54g symmetrical form factor',
      'Focus Pro 35K Gen-2 Optical Sensor with 99.8% resolution accuracy',
      'True 8000 Hz wireless polling rate support',
    ],
    specs: [
      { label: 'Weight', value: '54g Ultra-Light' },
      { label: 'Sensor', value: '35,000 DPI Focus Pro Gen-2' },
    ],
  },
  {
    id: 'steelseries-apex-pro',
    name: 'SteelSeries Apex Pro TKL Mechanical Keyboard',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Keyboards & Mice',
    label: 'Gaming Keyboard',
    price: 23499,
    originalPrice: 26999,
    glyph: 'APEX',
    wash: 'hsl(20 85% 55% / .3)',
    discountBadge: '-15%',
    platform: 'pc',
    coverImage: '/accessories/steelseries-apex-pro.jpg',
    rating: 4.89,
    reviewsCount: 2100,
    inStock: true,
    shortDesc: 'World’s fastest keyboard with OmniPoint 2.0 adjustable hyper-magnetic switches for 11x quicker response.',
    fullDesc: 'The Apex Pro TKL delivers rapid actuation from 0.2mm to 3.8mm, OLED smart display for in-game notifications, and aircraft-grade aluminum alloy top plate.',
    features: [
      'OmniPoint 2.0 Adjustable HyperMagnetic Switches',
      'Rapid Trigger technology for instant key reset without latency',
      'OLED Smart Display delivers info straight from games and apps',
    ],
    specs: [
      { label: 'Switches', value: 'OmniPoint 2.0 Magnetic' },
      { label: 'Layout', value: 'Tenkeyless (TKL)' },
    ],
  },
  {
    id: 'switch-pro-controller',
    name: 'Nintendo Switch™ Pro Controller',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Controllers',
    label: 'Gamepad',
    price: 7999,
    glyph: 'NSW',
    wash: 'hsl(0 80% 50% / .3)',
    platform: 'nintendo',
    coverImage: '/accessories/switch-pro-controller.jpg',
    rating: 4.88,
    reviewsCount: 5600,
    inStock: true,
    shortDesc: 'Take your game sessions up a notch with the Nintendo Switch Pro Controller. Includes motion controls and HD rumble.',
    fullDesc: 'Designed to go wherever you do, this controller features premium grip ergonomics, built-in amiibo functionality, and long-lasting 40-hour battery life.',
    features: [
      'HD Rumble built-in vibration feedback',
      'Integrated NFC touchpoint for scanning amiibo figures',
      'Ergonomic translucent matte frame',
    ],
    specs: [
      { label: 'Battery', value: 'Approx. 40 Hours' },
      { label: 'Platform', value: 'Nintendo Switch / PC' },
    ],
  },
  {
    id: 'playstation-vr2',
    name: 'PlayStation®VR2 Horizon Mountain Bundle',
    type: 'gear',
    category: 'accessories',
    subCategory: 'VR & Displays',
    label: 'Virtual Reality',
    price: 68999,
    originalPrice: 78000,
    glyph: 'PSVR2',
    wash: 'hsl(260 85% 65% / .3)',
    discountBadge: '-12%',
    platform: 'playstation',
    coverImage: '/accessories/playstation-vr2.jpg',
    rating: 4.93,
    reviewsCount: 980,
    inStock: true,
    shortDesc: 'Escape into worlds that feel truly real with 4K HDR visuals, eye tracking, headset feedback and 3D Audio.',
    fullDesc: 'Feel next-gen virtual reality immersion with stunning 4K HDR visuals, ground-breaking new controllers, and genre-defining games. Includes Horizon Call of the Mountain game voucher.',
    features: [
      'Dual 2000 x 2040 OLED displays delivering breathtaking 4K HDR at up to 120fps',
      'Intelligent eye tracking and foveated rendering',
      'Tempest 3D AudioTech and built-in headset haptic motor',
    ],
    specs: [
      { label: 'Display', value: '4K HDR OLED (2000x2040 per eye)' },
      { label: 'Refresh Rate', value: '90Hz / 120Hz' },
    ],
  },
  {
    id: 'elgato-streamdeck',
    name: 'Elgato Stream Deck MK.2 Studio Controller',
    type: 'gear',
    category: 'accessories',
    subCategory: 'Audio & Headsets',
    label: 'Stream Deck',
    price: 17999,
    originalPrice: 21999,
    glyph: 'DECK',
    wash: 'hsl(215 80% 55% / .3)',
    discountBadge: '-20%',
    platform: 'pc',
    coverImage: '/accessories/elgato-streamdeck.jpg',
    rating: 4.94,
    reviewsCount: 3100,
    inStock: true,
    shortDesc: '15 customizable LCD keys to control apps and platforms. Switch scenes, launch media, adjust audio and more.',
    fullDesc: 'Stream Deck gives you 15 customizable LCD keys to control your apps and tools. Trigger actions, launch social posts, adjust audio, play sound clips, and turn on lights at a single tap.',
    features: [
      '15 customizable LCD keys with tactile feedback',
      'One-touch operation: control OBS, Twitch, YouTube, Spotify, and more',
      'Detachable desktop stand and swappable custom faceplates',
    ],
    specs: [
      { label: 'Keys', value: '15 Customizable LCD Keys' },
      { label: 'Interface', value: 'USB 2.0 Type-C' },
    ],
  },
];

export function formatTaka(price: number): string {
  return `৳ ${price.toLocaleString('en-US')}`;
}

export const ALL_PRODUCTS: Product[] = [
  ...GAMES_STOREFRONT,
  ...ACCESSORIES_STOREFRONT,
  ...ACCESSORIES.filter(a => !ACCESSORIES_STOREFRONT.some(s => s.id === a.id)),
  ...GAMES.filter(g => !GAMES_STOREFRONT.some(s => s.id === g.id)),
  {
    id: 'ps5-slim',
    name: 'PlayStation®5 Slim / Disc Edition',
    type: 'consoles',
    category: 'consoles',
    subCategory: 'Consoles',
    label: 'Console',
    price: 499.99,
    glyph: 'PS5',
    wash: 'hsl(260 70% 65% / .26)',
    badge: '1TB HIGH-SPEED SSD',
    spec: 'Ultra-HD Disc Edition · Ray Tracing · 4K 120Hz',
    rating: 4.96,
    reviewsCount: 7800,
    inStock: true,
    shortDesc: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, adaptive triggers, and 3D Audio.',
    fullDesc: 'The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games. Slim design packs powerful gaming technology inside a sleek and compact console design.',
    features: [
      '1TB of ultra-fast integrated SSD storage keeps your favorite games ready and waiting',
      'Slim and compact form factor that fits seamlessly into modern setups',
      'Ultra HD Blu-ray disc drive allows playing 4K Blu-ray discs and physical game copies',
      'Ray Tracing delivers true-to-life reflections, refractions, and natural shadows',
      'Support for 4K 120Hz displays, HDR technology, and Tempest 3D AudioTech',
    ],
    specs: [
      { label: 'CPU', value: 'x86-64-AMD Ryzen Zen 2, 8 Cores / 16 Threads @ 3.5GHz' },
      { label: 'GPU', value: 'AMD Radeon RDNA 2-based engine with Ray Tracing' },
      { label: 'Memory', value: 'GDDR6 16GB, 448GB/s Bandwidth' },
      { label: 'Storage', value: '1TB Custom NVMe SSD (5.5GB/s Raw Read)' },
      { label: 'Video Output', value: 'HDMI 2.1 supporting 4K 120Hz, 8K, and VRR' },
    ],
  },
  {
    id: 'wallet-50',
    name: 'PlayStation® Store Wallet / $50 Card',
    type: 'top-ups',
    category: 'top-ups',
    subCategory: 'Digital Top-ups',
    label: 'Digital Code',
    price: 50.00,
    glyph: '$50',
    wash: 'hsl(290 85% 65% / .3)',
    badge: 'INSTANT DELIVERY',
    spec: 'Official PlayStation Store Digital Voucher',
    rating: 4.99,
    reviewsCount: 5200,
    inStock: true,
    shortDesc: 'Instant digital balance for games, add-ons, PlayStation Plus subscriptions, and movies on PlayStation Store.',
    fullDesc: 'Add funds to your PlayStation Network wallet without a credit card. Redeem for downloadable games, season passes, cosmetics, and monthly PlayStation Plus subscription plans.',
    features: [
      'Instant code generation upon purchase directly on screen and via email',
      'Zero expiration date: funds remain in your wallet until you choose to spend them',
      'Works seamlessly on PS5, PS4, and Web PlayStation Store',
    ],
    specs: [
      { label: 'Delivery', value: 'Instant Encrypted Digital Key' },
      { label: 'Region', value: 'US / Global PlayStation Network' },
      { label: 'Value', value: '$50.00 USD' },
    ],
  },
];

export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getGameById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id && (p.category === 'games' || p.type === 'games')) || GAMES.find(p => p.id === id);
}

export function getAccessoryById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id && (p.category === 'accessories' || p.type === 'gear')) || ACCESSORIES.find(p => p.id === id);
}
